### ISSUE TITLE
Use Vite instead of react-scripts

### ISSUE THREAD

**Issue by mark-wiemer** [mark-wiemer/math-with-mark#68]
react-scripts is a big old unmaintained black box. Build with [Vite](https://vitejs.dev/) instead.

**Comment by mark-wiemer** [comment]
commit 5d332a5

```
~/repos/math-with-mark (vite)
$ npm start
2023-04-12 22:38:15

> math-with-mark@0.1.0 start
> vite


  VITE v4.2.1  ready in 555 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
10:38:19 PM [vite] Internal server error: URI malformed
      at decodeURI (<anonymous>)
      at viteTransformMiddleware (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:61040:19)
      at call (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:48904:7)
      at next (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:48848:5)
      at file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:40757:28
      at viteServePublicMiddleware (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:40807:9)
      at call (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:48904:7)
      at next (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:48848:5)
      at next (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:48826:14)
      at cors (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:49380:7)
      at file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:49416:17
      at originCallback (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:49406:15)
      at file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:49411:13
      at optionsCallback (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:49391:9)
      at corsMiddleware (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:49396:7)
      at call (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:48904:7)
      at next (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:48848:5)
      at Function.handle (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:48851:3)
      at Server.app (file:///C:/Users/markw/repos/math-with-mark/node_modules/vite/dist/node/chunks/dep-79892de8.js:48716:37)
      at Server.emit (node:events:513:28)
      at parserOnIncoming (node:_http_server:1072:12)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

And from the browser devtools console:

```
react-mathquill.js:18 
 Uncaught ReferenceError: global is not defined
    at node_modules/react-mathquill/dist/react-mathquill.js (react-mathquill.js:18:4)
    at __require (chunk-4EOJPDL2.js?v=f7731fec:8:50)
    at node_modules/react-mathquill/index.js (index.js:6:20)
    at __require (chunk-4EOJPDL2.js?v=f7731fec:8:50)
    at index.js:7:1
   
node_modules/react-mathquill/dist/react-mathquill.js	@	react-mathquill.js:18
__require	@	chunk-4EOJPDL2.js?v=f7731fec:8
node_modules/react-mathquill/index.js	@	index.js:6
__require	@	chunk-4EOJPDL2.js?v=f7731fec:8
(anonymous)	@	index.js:7
```

**Comment by mark-wiemer** [comment]
[Vite 'global is not defined'](https://stackoverflow.com/questions/72114775/vite-global-is-not-defined), esp. comment linking https://github.com/bevacqua/dragula/issues/602#issuecomment-1109840139

**Comment by mark-wiemer** [comment]
https://github.com/vitejs/vite/issues/6482#issue-1100946741

Issue was `%` in `index.html`

**Comment by mark-wiemer** [comment]
[How to set PUBLIC_URL in create-react-app?](https://stackoverflow.com/questions/52136836/how-to-set-public-url-in-create-react-app)
